GET http://localhost:8080/emps/2
Content-Type: application/json

<> 2024-02-11T143955.200.json
<> 2024-02-11T143913.200.json

###
PUT http://localhost:8080/emps
Content-Type: application/json

{
  "id": 3,
  "image": "https://web-framework.oss-changzhou.aliyuncs.com/2022-09-03-07-37-38222.jpg",
  "username": "zhouyi",
  "name": "÷‹Ï⁄",
  "gender": 1,
  "job": 1,
  "entrydate": "2022-09-18",
  "deptId": 1
}

<> 2024-02-11T151155.400.json
<> 2024-02-11T151151.400.json
<> 2024-02-11T150707.415.json
###

POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "zhoujianbo",
  "password": "123456"
}

###
