##定义对象/Map集合
#user:
#  name: zhoujianbo
#  age: 21
#  address: jiangxi
#
##定义数组/List/Set
#hobby:
#  - java
#  - python
#  - C++
#  - C
##以上为.yml配置文件使用介绍

#阿里云OSS配置
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tM2A13UsKov6f6SZYcx
    accessKeySecret: DyLSqyQXhZfXLRrgWelnrfZzFZTU13
    bucketName: first-use-oss

#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug