#定义对象/Map集合
user:
  name: zhoujianbo
  age: 21
  address: jiangxi

#定义数组/List/Set
hobby:
  - java
  - python
  - C++
  - C

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tM2A13UsKov6f6SZYcx
    accessKeySecret: DyLSqyQXhZfXLRrgWelnrfZzFZTU13
    bucketName: first-use-oss